### ISSUE TITLE
Xallarap TO-DO list

### ISSUE THREAD

**Issue by rpoleski** [rpoleski/MulensModel#86]
What to do in `xal` branch:

- [x] Check if there is something useful in `xallarap` branch; delete that branch afterwards.
- [x] Should orbit reference epoch be one of possible xallarap parameters? Note that we already have `t_0_xi` (typically equal to `t_0_par`) - NOT at this point.
- [x] Update `documents/parameter_names.tex`.
- [x] `xi_Omega_node` and `xi_argument_of_latitude_reference` - docstrings in modelparameters.py.
- [x] `Trajectory._get_shifts_xallarap()` - I think we can call Orbit class there and don't have to try OrbitCircular directly. This change will simplify the code.
- [x] Add tests to `ModelParameters._check_valid_combination_1_source_standard()`.
- [x] Xallarap and binary source are currently forbidden - UNIT TEST
- [x] Xallarap and Cassan08 parameterization are forbidden
- [x] Xallarap and chi2 gradient - currently forbidden - UNIT TEST
- [x] consider removing `*args` from `Orbit.__new__()`, so that it's the parameters uniquely define the child class
- [x] Parallax and xallarap - Do relative mu in both have to agree? Answer: no.
- [x] Test `Model._plot_arrow()`.
- [x] Check if all examples work. **2023-07-13: xal: [bc038e8](https://github.com/rpoleski/MulensModel/commit/bc038e8d5b72ecf2ba115282491b6431c93cffb4) master: [cb303e4](https://github.com/rpoleski/MulensModel/commit/cb303e414187458fd0511999b5b83bcaa7b6627d); issues: 1) last plot in ex20**
- [x] eccentricity in MM - see the list of tasks in the post below (on Jul 13)
- [x] Add link to wiki on orbital parameters definitions ([wiki1](https://en.wikipedia.org/wiki/Orbital_elements), [wiki2](https://en.wikipedia.org/wiki/Argument_of_latitude), image from wiki). 
- [x] lines marked "XXX" in modelparameters.py.
- [x] Docstrings for added tests.
- [x] For `OrbitCircular` change: `periapsis_epoch` -> `ascending_node_epoch`
- [x] AT THE END - flake8, version number, sphinx, README.md

**Comment by rpoleski** [comment]
Changes to example 16 from the comit b97f2a5 are also useful for the master branch. They allow to read starting points from a file in EMCEE fitting.

**Comment by rpoleski** [comment]
Eccentric orbit requires updates:

- [ ] `documents/parameter_names.tex`
- [ ] `ModelParameters.__repr__()`
- [ ] `ModelParameters._check_valid_combination_1_source_xallarap()`
- [ ] `ModelParameters._check_valid_combination_1_source()`
- [ ] `ModelParameters._check_valid_combination_1_source_standard()`
- [ ] `ModelParameters._set_parameters()`
- [ ] `ModelParameters` - add parameters there 
- [ ] `test_xallarap_at_t_0()`
- [ ] `test_xallarap_at_t_0_plus_half_of_period_1()`

**Comment by rpoleski** [comment]
@jenniferyee 

1. Do you want to review this code once more before merging? __Please let me know ASAP.__ If not, then I'd like to merge it on Monday.
2. Do you think I should change class name: `OrbitCircular` -> `CircularOrbit`? For me, the former has an advantage of being ready to be expanded in a logical way, e.g., `OrbitCircularFromStateVector`.

**Comment by rpoleski** [comment]
@jenniferyee - one more point to discuss: should the xallarap parameters start with `xi_` or with `chi_`? I think I've seen both conventions in the papers.

**Comment by rpoleski** [comment]
I've just found that recent papers ([Miyake et al. 2012](https://ui.adsabs.harvard.edu/abs/2012ApJ...752...82M/abstract), [Miyazaki et al. 2020](https://ui.adsabs.harvard.edu/abs/2020AJ....159...76M/abstract), [Rota et al. 2021](https://ui.adsabs.harvard.edu/abs/2021AJ....162...59R/abstract)) use Greek xi for the xallarap parameters, so I'll stay with that if there are no other comments today.

**Comment by rpoleski** [comment]
Merged.
264 unit tests and 74% coverage of code using tests at this point.

**Comment by jenniferyee** [comment]
woot woot!
--------------------------------------------------------------
Dr. Jennifer C. Yee
(she/her)

Office: P-341
Center for Astrophysics | Harvard & Smithsonian
60 Garden St, MS-15
Cambridge, MA 02138
--------------------------------------------------------------
